name: Test and Publish the package

on:
  pull_request:
    branches:
    - master
  push:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Formatting (pre-commit)
      uses: pre-commit/action@v2.0.3
    - name: Setup poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Type checking
      run: poetry run mypy .
    - name: Linting
      run: |
        poetry run pylint --rcfile=.pylint.cfg throttled
        poetry run pylint --rcfile=.pylint.cfg --disable=redefined-outer-name tests

  tests:
    needs:
    - checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Setup poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Testing
      run: poetry run pytest --cov=throttled --cov-report=xml tests
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
