name: Test and Publish the package

on:
  pull_request:
    branches:
    - master
  push:
    tags:
    - '*.*.*'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Setup poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Extract dependencies
      run: poetry export --dev > requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Formatting (pre-commit)
      uses: pre-commit/action@v2.0.3
    - name: Type checking
      run: mypy .
    - name: Linting
      run: |
        pylint --rcfile=.pylint.cfg throttled
        pylint --rcfile=.pylint.cfg --disable=redefined-outer-name tests

  tests:
    needs:
    - checks
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
        fastapi_version: [0.65, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python_version: ${{matrix.python_version}}
    - name: Setup poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Extract dependencies
      run: poetry export --dev > requirements.txt
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install fastapi==${{matrix.fastapi_version}}
    - name: Testing
      run: pytest tests

  deploy:
    needs:
    - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: abatilo/actions-poetry@v2.0.0
    - name: Configure Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    - name: Build and Publish
      run: |
        poetry build
        poetry publish
